name: Release dump.json

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dump.json"
          body: "Dumped on: ${{ env.DATE }}"
